"""The last three review findings: the spec-vs-code comparison, and two "MCP only" guards.

The spec-vs-code one is the most consequential defect the review found, because its output does
not go through the verify agent — the pipeline appends it straight to `verified`, so a wrong
answer draws a real `api_schema` band-aid with nothing downstream to challenge it.
"""
from __future__ import annotations

import textwrap

import pytest

from vpcopilot.inputs.openapi import orphans
from vpcopilot.routes import collect_route_context


@pytest.fixture
def flask_app(tmp_path):
    """Three routes, declared the ordinary way. `collect_route_context` is the real producer —
    the existing `orphans` tests hand-write path-shaped lines the caller never actually supplies,
    which is precisely why the producer/consumer mismatch survived."""
    (tmp_path / "app.py").write_text(textwrap.dedent('''
        @app.route("/api/pay", methods=["POST"])
        def pay(): ...
        @app.route("/api/login", methods=["POST"])
        def login(): ...
        @app.route("/api/secret-admin", methods=["GET"])
        def admin(): ...
    '''))
    return collect_route_context(str(tmp_path)).splitlines()


SPEC = {"paths": {"/api/pay": {"post": {}}, "/api/login": {"post": {}}, "/api/gone": {"get": {}}}}


def test_a_served_undeclared_route_is_found(flask_app):
    """The direction `orphans`' own docstring calls "the one that bites" — an `api_schema` band-aid
    built from the spec would start rejecting it the moment it is applied.

    It was reported NOWHERE. `served` was populated only from an in-repo OpenAPI file and never
    from code in any configuration, because a registration line's last whitespace token is
    `methods=["POST"])`, not a path."""
    got = orphans(SPEC, flask_app)
    assert got["code_only"] == ["/api/secret-admin"]


def test_the_routes_the_app_really_serves_are_not_called_unserved(flask_app):
    """The inverse false positive, and the louder one: /api/pay and /api/login ARE served, and the
    run reported both as "declared in the spec but served by no route in the code"."""
    got = orphans(SPEC, flask_app)
    assert got["matched"] == ["/api/login", "/api/pay"]
    assert "/api/pay" not in got["spec_unverified"]


def test_an_unmatched_declaration_is_reported_as_unverified_not_as_an_orphan(flask_app):
    """The design decision, and the reason this is not simply "extract paths better".

    `code_only` is a PRESENCE claim — the sweep found this route in the source — and a source
    sweep can establish presence. The other direction is an ABSENCE claim: "nothing serves this".
    A line-wise grep cannot establish that. File-based routing (`app/api/pay/route.js`) declares a
    route with no line to match; a dynamically mounted router never appears literally. So the
    unmatched declarations are reported as NOT CHECKED, and the old `spec_only` key is gone rather
    than left empty for someone to reach for again."""
    got = orphans(SPEC, flask_app)
    assert got["spec_unverified"] == ["/api/gone"]
    assert "spec_only" not in got, "the key that asserted absence must not survive as an empty list"


def test_a_sweep_that_found_nothing_is_not_a_spec_full_of_orphans():
    """Two states that used to print identically. A repo whose routes the sweep cannot see (file
    -based routing, a framework with no literal registration lines) produced `served == {}`, so
    EVERY declared endpoint became an orphan — a confident finding generated by a failed sweep."""
    got = orphans(SPEC, ["Route registrations (framework code):"])
    assert got["swept"] is False
    assert got["code_only"] == []
    assert sorted(got["spec_unverified"]) == ["/api/gone", "/api/login", "/api/pay"], \
        "the declarations are still reported — as unchecked, not as orphaned"


def test_the_pipeline_only_raises_a_finding_for_the_claim_it_can_support():
    """The finding bypasses verify (`findings.append` + `verified.append`), so nothing downstream
    challenges it and triage can draw a real api_schema band-aid from it. It must therefore only
    ever assert the direction the evidence supports."""
    from pathlib import Path
    src = (Path(__file__).resolve().parents[1] / "src/vpcopilot/pipeline.py").read_text()
    assert 'if spec_orphans and spec_orphans.get("code_only"):' in src, \
        "the orphan finding still fires on the unsupportable absence claim"
    assert "cannot prove absence" in src, "the log must say what was not established"


# ---------------------------------------------------------------- input paths, on every surface


MISSING = "/does/not/exist/at/all"


def test_the_cli_refuses_a_repo_path_that_does_not_exist():
    """`run_pipeline`'s own docstring calls this "the failure mode not to extend" — and the check
    existed only in mcp.py, so the CLI and console ran the pipeline to completion and wrote a
    clean-bill-of-health summary.json for a directory that was never read."""
    from typer.testing import CliRunner

    from vpcopilot import cli
    res = CliRunner().invoke(cli.app, ["scan", MISSING, "--out", "/tmp/vpc-nope"])
    assert res.exit_code != 0


def test_the_console_refuses_it_before_the_scan_starts(monkeypatch):
    """On the REQUEST thread. Raising inside the pipeline would surface as a job error after the
    endpoint had already returned 200 "running" — the operator would see a scan start, then fail.

    Also asserts the scanner is not left claimed: a refusal that wedges the console is worse than
    the thing it refused."""
    from fastapi.testclient import TestClient

    from vpcopilot.console import app as A
    A._scan.update(state="idle")
    res = TestClient(A.app).post("/api/scan", json={"repo": MISSING, "out": "/tmp/vpc-nope"})
    assert res.status_code == 400
    assert "does not exist" in res.json()["detail"]
    assert A._scan["state"] != "running", "the refusal left the scanner claimed"


def test_all_three_surfaces_share_one_implementation():
    """The guard lives in `pipeline.validate_scan_inputs`, so a fourth consumer inherits it. The
    defect was one surface having a copy and the others having nothing."""
    from pathlib import Path

    from vpcopilot.pipeline import validate_scan_inputs
    with pytest.raises(ValueError, match="does not exist"):
        validate_scan_inputs(repo_path=MISSING)
    with pytest.raises(ValueError, match="spec"):
        validate_scan_inputs(spec_path=MISSING)
    with pytest.raises(ValueError, match="manifest"):
        validate_scan_inputs(manifest_paths=[MISSING])
    validate_scan_inputs(repo_path=None, spec_path=None, manifest_paths=[])   # must not raise

    root = Path(__file__).resolve().parents[1] / "src/vpcopilot"
    assert "validate_scan_inputs" in (root / "console/app.py").read_text()
